from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
excluded = {
    'voice_manager.c',
    'voice_trigger.c',
    'wake_word_tflite.cpp',
    'wake_word_microfrontend.c',
    'wake_word_fft.cpp',
    'wake_word_fft_util.cpp',
    'wake_word_kiss_fft_int16.cpp',
}
src = [item for item in src if os.path.basename(str(item)) not in excluded]
CPPPATH = [
    cwd,
    Dir('#/applications/common'),
    Dir('#/vendor_btstack/btstack/wiced_include'),
    Dir('#/vendor_btstack/btstack_integration/COMPONENT_HCI-UART/include'),
    Dir('#/vendor_btstack/btstack_integration/COMPONENT_HCI-UART/common'),
    Dir('#/vendor_btstack/abstraction_rtos/include'),
]

LIBPATH = [
    Dir('#/vendor_btstack/lib/COMPONENT_CM33/COMPONENT_SOFTFP/TOOLCHAIN_GCC_ARM'),
]
LIBS = ['libbtstack.a']

group = DefineGroup('AppM33', src, depend=[''], CPPPATH=CPPPATH, LIBS=LIBS, LIBPATH=LIBPATH)
Return('group')
