import rtconfig
from building import *
import os

cwd  = GetCurrentDir()
path = [
    cwd,
    os.path.join(cwd, 'ifx_deepcraft', 'include'),
    os.path.join(cwd, 'ifx_deepcraft', 'source'),
    os.path.join(cwd, 'ifx_deepcraft', 'source', 'va_core'),
    os.path.join(cwd, 'ifx_deepcraft', 'models'),
    os.path.join(cwd, 'ifx_deepcraft', 'models', 'Smart_Lights_Demo'),
]
src  = Glob('*.c') + Glob('*.cpp')
src  = [f for f in src if os.path.basename(str(f)) not in [
    'model_deployment.c',
    'model_input_bridge.c',
    'motor7_model_runner.c',
    'wake_word_detector.cpp',
]]

defines = [
    'XIAOZHI_WAKE_USE_IFX_DEEPCRAFT',
    'PROJECT_PREFIX=Smart_Lights_Demo',
    'ENABLE_IFX_SOD',
    'ENABLE_IFX_PRE_PROCESS_HPF',
    'ENABLE_IFX_VA_WWD',
    'TF_LITE_STATIC_MEMORY',
    'ETHOSU55',
    'COMPONENT_U55',
    'COMPONENT_ML_TFLM',
    'XIAOZHI_DEEPCRAFT_WW_ONLY',
]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path, CPPDEFINES = defines)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
