import rtconfig
from building import *
import os

cwd  = GetCurrentDir()
default_ei_root = os.path.abspath(os.path.join(
    cwd,
    '..',
    '..',
    '..',
    'repo',
    'Extract',
    'Board_Support_Packages',
    'Infineon',
    'PSOC_E84-EDGI-TALK',
    '1.1.0',
    'projects',
    'Edgi_Talk_M55_XiaoZhi',
    'edge-impulse'))
wake_backend = os.environ.get('XIAOZHI_WAKE_BACKEND', 'edge_impulse')
edge_impulse_root = os.environ.get('XIAOZHI_EDGE_IMPULSE_ROOT', default_ei_root)
edge_impulse_enabled = wake_backend == 'edge_impulse' and os.path.isdir(edge_impulse_root)
deepcraft_enabled = wake_backend == 'deepcraft'

path = [
    cwd,
    os.path.join(cwd, 'ifx_deepcraft', 'include'),
    os.path.join(cwd, 'ifx_deepcraft', 'source'),
    os.path.join(cwd, 'ifx_deepcraft', 'source', 'va_core'),
    os.path.join(cwd, 'ifx_deepcraft', 'models'),
    os.path.join(cwd, 'ifx_deepcraft', 'models', 'Smart_Lights_Demo'),
]
src  = Glob('*.c') + Glob('*.cpp')
src  = [f for f in src if os.path.basename(str(f)) not in [
    'model_deployment.c',
    'model_input_bridge.c',
    'motor7_model_runner.c',
    'wake_word_detector.cpp',
]]
if not edge_impulse_enabled:
    src = [f for f in src if os.path.basename(str(f)) != 'xiaozhi_edge_impulse_wake_backend.cpp']
else:
    src = [f for f in src if os.path.basename(str(f)) != 'xiaozhi_edge_impulse_wake_backend.cpp']

defines = [
    'PROJECT_PREFIX=Smart_Lights_Demo',
    'ENABLE_IFX_SOD',
    'ENABLE_IFX_PRE_PROCESS_HPF',
    'ENABLE_IFX_VA_WWD',
    'TF_LITE_STATIC_MEMORY',
    'ETHOSU55',
    'COMPONENT_U55',
    'COMPONENT_ML_TFLM',
    'XIAOZHI_DEEPCRAFT_WW_ONLY',
]

if edge_impulse_enabled:
    defines += ['XIAOZHI_WAKE_USE_EDGE_IMPULSE_TFLM']
elif deepcraft_enabled:
    defines += ['XIAOZHI_WAKE_USE_IFX_DEEPCRAFT']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path, CPPDEFINES = defines)

if edge_impulse_enabled:
    ei_sdk_rel = os.path.join('edge-impulse-sdk')
    ei_sdk_root = os.path.join(edge_impulse_root, ei_sdk_rel)
    ei_src = [os.path.join(cwd, 'xiaozhi_edge_impulse_wake_backend.cpp')]
    ei_path = [
        edge_impulse_root,
        os.path.join(edge_impulse_root, 'tflite-model'),
    ]
    ei_cflags = ''
    ei_cxxflags = ' -std=c++11 -fno-rtti -fno-exceptions -fno-threadsafe-statics -Wno-sign-compare -Wno-strict-aliasing'
    group = group + DefineGroup('XiaoZhiEdgeImpulseWake',
                                ei_src,
                                depend=[''],
                                CPPPATH=ei_path,
                                CPPDEFINES=['XIAOZHI_WAKE_USE_EDGE_IMPULSE_TFLM'],
                                LOCAL_CFLAGS=ei_cflags,
                                LOCAL_CXXFLAGS=ei_cxxflags)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        if (item == 'ifx_deepcraft') and (not deepcraft_enabled):
            continue
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
