#ifndef XIAOZHI_WAKE_FEEDBACK_AUDIO_H
#define XIAOZHI_WAKE_FEEDBACK_AUDIO_H

#include <rtthread.h>

#define XIAOZHI_WAKE_FEEDBACK_SAMPLE_RATE 16000U
#define XIAOZHI_WAKE_FEEDBACK_CHANNELS 1U
#define XIAOZHI_WAKE_FEEDBACK_BITS_PER_SAMPLE 16U
#define XIAOZHI_WAKE_FEEDBACK_WOZAI_SAMPLES 10860U

extern const rt_int16_t g_xiaozhi_wake_feedback_wozai_pcm[XIAOZHI_WAKE_FEEDBACK_WOZAI_SAMPLES];

#endif
