from __future__ import annotations


PRODUCT_SCOPE = [
    "software-project",
    "embedded-board",
    "robotics",
    "education-mode",
    "developer-mode",
]

RUNTIME_SCOPE = [
    "browser",
    "desktop-computer",
    "development-board",
    "multi-computer-runner",
    "future-3d-client",
]

PRIMARY_LOOP = [
    "user-goal",
    "project-generator",
    "environment-builder",
    "wiring-or-dependency-plan",
    "ai-coach",
    "debug-console",
    "simulation-first",
    "human-approval-for-risk",
    "delivery-workshop",
]

DEVELOPMENT_WORKSHOP_MODULES = [
    {
        "id": "project-generator",
        "label": "项目生成器",
        "station": "项目办公室 / 需求信箱",
        "map_scene": "map-farm",
        "map_location": "农舍门口与需求信箱之间",
        "detail": "把用户目标转换成项目计划、模块、验收标准、任务链和可交给 AI 的工作单。",
        "modes": ["2D 开发者", "2D 教育版", "3D 开发者", "3D 教育版"],
        "backend_anchor": "/api/development/projects/{project_id}/framework#project-generator",
        "runner_capabilities": ["repo-clone", "template-expand", "task-split"],
        "ai_responsibilities": ["clarify-goal", "draft-plan", "split-tasks", "write-acceptance"],
        "npc_role_templates": ["requirement-clarifier", "project-planner", "acceptance-writer"],
        "assignment_keywords": ["project-generator", "requirement", "planning", "acceptance"],
        "next_actions": ["connect-requirement-inbox", "create-requirement-draft", "seed-task-plots"],
        "approval_policy": "普通软件和文档规划可自动推进；采购、真实设备动作和发布动作需要人工确认。",
        "risk_level": "low",
    },
    {
        "id": "environment-builder",
        "label": "环境搭建器",
        "station": "电脑车间 / Runner 机房",
        "map_scene": "map-farm",
        "map_location": "牛棚入口与机房中控",
        "detail": "根据项目类型选择仓库、工具链、依赖安装和验证命令；跨电脑时本地路径由各电脑自己确定。",
        "modes": ["developer-mode", "multi-computer-collaboration"],
        "backend_anchor": "/api/runners + /api/collaboration/projects/{project_id}/computer-nodes",
        "runner_capabilities": ["github-clone", "dependency-install", "build-test", "workspace-report"],
        "ai_responsibilities": ["detect-capabilities", "draft-install-plan", "schedule-validation", "report-environment"],
        "npc_role_templates": ["environment-builder", "runner-inspector", "dependency-installer"],
        "assignment_keywords": ["environment-builder", "environment", "runner", "dependency", "computer"],
        "next_actions": ["attach-computer-manager", "persist-runner-capabilities", "write-environment-status"],
        "approval_policy": "安装命令先给用户可见确认；不默认改系统级配置。",
        "risk_level": "medium",
    },
    {
        "id": "wiring-bom",
        "label": "连线选型台",
        "station": "硬件实验区 / 工具棚外场",
        "map_scene": "map-farm",
        "map_location": "工具棚和审批门岗之间",
        "detail": "结构化器件清单、BOM、引脚连线、供电风险和采购建议，也可服务纯软件项目的依赖清单。",
        "modes": ["embedded", "robotics", "education-lab", "software-dependency-plan"],
        "backend_anchor": "/api/development/projects/{project_id}/framework#wiring-bom",
        "runner_capabilities": ["bom-validate", "pinout-lookup", "document-generate"],
        "ai_responsibilities": ["complete-bom", "mark-pinout", "detect-power-risk", "draft-purchase-notes"],
        "npc_role_templates": ["bom-curator", "wiring-reviewer", "power-risk-reviewer"],
        "assignment_keywords": ["wiring-bom", "bom", "wiring", "pinout", "power"],
        "next_actions": ["add-component-knowledge", "connect-lab-records", "connect-approval-gate"],
        "approval_policy": "任何真实接线、上电、烧录前都必须有人确认。",
        "risk_level": "high",
    },
    {
        "id": "debug-console",
        "label": "可视化调试台",
        "station": "串口电视 / 调试控制台",
        "map_scene": "map-home",
        "map_location": "主房电视机，也可从电脑车间进入",
        "detail": "统一串口收发、USB 扫描、日志采集和数字波形显示；协议先走 AICSV/1，后续兼容更多仪器。",
        "modes": ["serial", "usb", "log", "waveform"],
        "backend_anchor": "/api/collaboration/projects/{project_id}/runner-commands",
        "runner_capabilities": ["serial-scan", "serial-open", "serial-write", "waveform-parse"],
        "ai_responsibilities": ["explain-log", "draft-serial-command", "spot-waveform-anomaly", "archive-lab-record"],
        "npc_role_templates": ["serial-debugger", "waveform-analyst", "log-interpreter"],
        "assignment_keywords": ["debug-console", "serial", "usb", "waveform", "log"],
        "next_actions": ["reuse-serial-tv", "enforce-runner-serial-whitelist", "persist-waveform-frames"],
        "approval_policy": "串口写入、参数改写默认属于高风险动作，需要审批或现场确认。",
        "risk_level": "high",
    },
    {
        "id": "ai-coach",
        "label": "AI 教练站",
        "station": "NPC 管理 / 聊天小院",
        "map_scene": "map-farm",
        "map_location": "鸡舍聊天区与 NPC 精灵区",
        "detail": "教育模式里一步一步教；开发模式里把 Codex、Claude、Qwen 等 NPC 分成资料、实现、测试、验收角色。",
        "modes": ["education-mode", "developer-mode", "multi-npc-collaboration"],
        "backend_anchor": "/api/collaboration/projects/{project_id}/thread-workstations",
        "runner_capabilities": ["provider-adapter", "thread-inbox", "final-reply-sync"],
        "ai_responsibilities": ["recommend-next-step", "dispatch-work", "minimal-ack", "final-reply", "handoff-summary"],
        "npc_role_templates": ["learning-coach", "collaboration-dispatcher", "final-reply-closer"],
        "assignment_keywords": ["ai-coach", "coach", "dispatch", "final-reply", "handoff"],
        "next_actions": ["wire-claude-qwen-adapters", "persist-npc-knowledge", "treat-final-reply-pool-as-truth"],
        "approval_policy": "软件任务可自动续推；硬件、花钱、发布、删库等动作转人工审核。",
        "risk_level": "medium",
    },
    {
        "id": "simulation-lab",
        "label": "仿真数字孪生",
        "station": "实验洞口 / 仿真台",
        "map_scene": "map-toolshed",
        "map_location": "工具棚内部实验洞口",
        "detail": "先在仿真里完成接线、示例运行、数据回放和 AI 判定，再进入真机实验。",
        "modes": ["education-first", "hardware-preflight", "robotics-ros"],
        "backend_anchor": "/api/lab/short-chain + future /api/simulations",
        "runner_capabilities": ["simulation-run", "log-replay", "artifact-capture"],
        "ai_responsibilities": ["draft-simulation-steps", "check-result", "report-risk", "decide-hardware-readiness"],
        "npc_role_templates": ["simulation-tester", "lab-record-keeper", "hardware-preflight-reviewer"],
        "assignment_keywords": ["simulation-lab", "simulation", "digital-twin", "preflight", "lab"],
        "next_actions": ["define-simulation-task-model", "archive-screenshot-video", "link-approval-gate"],
        "approval_policy": "仿真可自动跑；真机准备、烧录、执行器动作必须过审批门岗。",
        "risk_level": "high",
    },
]

GUARDRAILS = [
    {
        "id": "firmware_flash",
        "label": "烧录 / 刷机",
        "reason": "可能改变真实设备状态，失败时会造成设备不可用或需要回滚。",
        "required_gate": "approval-gate + lab-preflight + human-confirmation",
    },
    {
        "id": "parameter_write",
        "label": "参数写入 / 串口写入",
        "reason": "可能改变控制参数、电机限位、通信配置或现场设备行为。",
        "required_gate": "approval-gate + visible-command-preview",
    },
    {
        "id": "actuator_motion",
        "label": "执行器 / 电机 / 机械臂动作",
        "reason": "涉及现实安全风险，不能被游戏化成一键自动执行。",
        "required_gate": "approval-gate + onsite-human-confirmation + emergency-stop-check",
    },
]


def get_development_framework(project_id: str | None = None) -> dict:
    return {
        "project_id": project_id,
        "product_scope": PRODUCT_SCOPE,
        "runtime_scope": RUNTIME_SCOPE,
        "primary_loop": PRIMARY_LOOP,
        "modules": DEVELOPMENT_WORKSHOP_MODULES,
        "guardrails": GUARDRAILS,
    }
