from setuptools import setup

package_name = 'rehab_arm_psoc_bridge'

setup(
    name=package_name,
    version='0.1.0',
    packages=[package_name],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='HalloYang06',
    maintainer_email='2735283977@qq.com',
    description='NanoPi bridge from ROS JointTrajectory to PSoC CAN command frames',
    license='MIT',
    entry_points={
        'console_scripts': [
            'psoc_can_bridge_node = rehab_arm_psoc_bridge.psoc_can_bridge_node:main',
            'data_recorder_node = rehab_arm_psoc_bridge.data_recorder_node:main',
            'camera_keyframe_node = rehab_arm_psoc_bridge.camera_keyframe_node:main',
            'stereo_vision_context = rehab_arm_psoc_bridge.stereo_vision_context:main',
            'stereo_camera_capture_upload = rehab_arm_psoc_bridge.stereo_camera_capture_upload:main',
            'joint_state_motor_state_node = rehab_arm_psoc_bridge.joint_state_motor_state_node:main',
            'jsonl_replay_node = rehab_arm_psoc_bridge.jsonl_replay_node:main',
            'check_recording = rehab_arm_psoc_bridge.check_recording:main',
            'summarize_recording = rehab_arm_psoc_bridge.summarize_recording:main',
            'build_replay_plan = rehab_arm_psoc_bridge.build_replay_plan:main',
            'validate_recording_quality = rehab_arm_psoc_bridge.validate_recording_quality:main',
            'export_recording_csv = rehab_arm_psoc_bridge.export_recording_csv:main',
            'build_manifest = rehab_arm_psoc_bridge.build_manifest:main',
            'build_annotation_queue = rehab_arm_psoc_bridge.build_annotation_queue:main',
            'export_annotation_template = rehab_arm_psoc_bridge.export_annotation_template:main',
            'validate_annotations = rehab_arm_psoc_bridge.validate_annotations:main',
            'build_dataset_index = rehab_arm_psoc_bridge.build_dataset_index:main',
            'sync_dry_run = rehab_arm_psoc_bridge.sync_dry_run:main',
            'sync_upload = rehab_arm_psoc_bridge.sync_upload:main',
            'check_server_quality_gate = rehab_arm_psoc_bridge.check_server_quality_gate:main',
            'sync_test_server = rehab_arm_psoc_bridge.sync_test_server:main',
            'candump_motor_telemetry = rehab_arm_psoc_bridge.candump_motor_telemetry:main',
            'check_m33_motor_status_presence = rehab_arm_psoc_bridge.check_m33_motor_status_presence:main',
            'feedback_source_readiness = rehab_arm_psoc_bridge.feedback_source_readiness:main',
            'calibration_observation = rehab_arm_psoc_bridge.calibration_observation:main',
            'board_manifest = rehab_arm_psoc_bridge.board_manifest:main',
            'board_manifest_sync_dry_run = rehab_arm_psoc_bridge.board_manifest_sync_dry_run:main',
            'board_manifest_sync_upload = rehab_arm_psoc_bridge.board_manifest_sync_upload:main',
            'validate_patient_profile = rehab_arm_psoc_bridge.validate_patient_profile:main',
            'build_patient_profile_template = rehab_arm_psoc_bridge.build_patient_profile_template:main',
            'check_patient_profile_release_gate = rehab_arm_psoc_bridge.check_patient_profile_release_gate:main',
            'export_m33_safety_subset = rehab_arm_psoc_bridge.export_m33_safety_subset:main',
            'review_patient_profile_change = rehab_arm_psoc_bridge.review_patient_profile_change:main',
            'build_ble_m33_safety_package = rehab_arm_psoc_bridge.build_ble_m33_safety_package:main',
            'motion_test_report = rehab_arm_psoc_bridge.motion_test_report:main',
            'bench_motion_sequence = rehab_arm_psoc_bridge.bench_motion_sequence:main',
            'motor_profiles = rehab_arm_psoc_bridge.motor_profiles:main',
            'build_voice_pipeline_plan = rehab_arm_psoc_bridge.build_voice_pipeline_plan:main',
            'build_rehab_session_plan = rehab_arm_psoc_bridge.build_rehab_session_plan:main',
            'build_command_center_sync_plan = rehab_arm_psoc_bridge.build_command_center_sync_plan:main',
            'check_command_center_sync_plan = rehab_arm_psoc_bridge.check_command_center_sync_plan:main',
            'check_vla_plan_candidate = rehab_arm_psoc_bridge.check_vla_plan_candidate:main',
            'build_mujoco_dry_run_review_plan = rehab_arm_psoc_bridge.build_mujoco_dry_run_review_plan:main',
            'check_operator_review = rehab_arm_psoc_bridge.check_operator_review:main',
        ],
    },
)
