"use client";

import integrations from "../../../../lib/open-source-integrations.json";
import styles from "./robotics.module.css";

const toolIds = ["foxglove", "robotwebtools", "plotjuggler", "robot-descriptions"];
const tools = integrations.filter((item) => toolIds.includes(item.id));

function downloadText(fileName: string, content: string, type = "application/json") {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function buildFoxgloveLayout() {
  return {
    name: "AI Collab Robot Field",
    panels: [
      { type: "3D", title: "Robot model / TF / map", topics: ["/robot_description", "/tf", "/joint_states", "/map"] },
      { type: "RawMessages", title: "Joint states", topics: ["/joint_states"] },
      { type: "Image", title: "Front camera", topics: ["/camera/front/image_raw"] },
    ],
    notes: "Generated by AI Collab Platform. Use with Foxglove 3D panel and your ROS/Foxglove bridge.",
  };
}

function buildRosbridgeConfig() {
  return {
    mode: "readonly",
    bridge: "ws://127.0.0.1:9090",
    subscribe: ["/robot_description", "/tf", "/joint_states", "/camera/front/image_raw", "/imu/data"],
    blockedActions: ["publish", "serviceCall", "actionGoal"],
    approvalRequired: ["hardware_motion", "serial_write", "deployment", "rollback"],
  };
}

function buildPlotJugglerCsv() {
  const rows = ["time,audio_rms,imu_acc_x,joint_1"];
  for (let i = 0; i < 40; i += 1) {
    rows.push(`${(i * 0.02).toFixed(2)},${(0.3 + Math.sin(i / 4) * 0.2).toFixed(3)},${(0.02 + Math.cos(i / 5) * 0.03).toFixed(3)},${(1.2 + Math.sin(i / 8) * 0.4).toFixed(3)}`);
  }
  return rows.join("\n");
}

function buildRobotCatalogSeed() {
  return {
    source: "robot_descriptions.py style index",
    policy: "Store only project index and license/source metadata; do not vendor large mesh assets into this repo.",
    models: [
      { name: "panda", type: "arm", expectedDof: 7, formats: ["URDF", "MJCF"], status: "candidate" },
      { name: "ur5e", type: "arm", expectedDof: 6, formats: ["URDF"], status: "candidate" },
      { name: "go2", type: "quadruped", expectedDof: 12, formats: ["URDF"], status: "candidate" },
    ],
  };
}

function runAction(id: string) {
  if (id === "foxglove") {
    downloadText("foxglove-robot-field-layout.json", JSON.stringify(buildFoxgloveLayout(), null, 2));
    return;
  }
  if (id === "robotwebtools") {
    downloadText("rosbridge-readonly-config.json", JSON.stringify(buildRosbridgeConfig(), null, 2));
    return;
  }
  if (id === "plotjuggler") {
    downloadText("plotjuggler-telemetry-sample.csv", buildPlotJugglerCsv(), "text/csv");
    return;
  }
  if (id === "robot-descriptions") {
    downloadText("robot-model-catalog-seed.json", JSON.stringify(buildRobotCatalogSeed(), null, 2));
  }
}

export function ToolActionPanel() {
  return (
    <div className={styles.externalList}>
      {tools.map((tool) => (
        <article key={tool.id}>
          <strong>{tool.name}</strong>
          <small>{tool.runnerUse}</small>
          <button type="button" data-testid={`robotics-tool-${tool.id}`} onClick={() => runAction(tool.id)}>
            {tool.platformAction}
          </button>
          <a href={tool.github} target="_blank" rel="noreferrer">源码</a>
        </article>
      ))}
    </div>
  );
}
