"""initial_schema

Revision ID: d41db472ac7c
Revises: 
Create Date: 2026-05-06 17:44:33.525995

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd41db472ac7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_task_id'), ['task_id'], unique=False)

    op.create_table('collaboration_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('approval_id', sa.String(length=64), nullable=True),
    sa.Column('handoff_id', sa.String(length=64), nullable=True),
    sa.Column('requirement_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('dispatch_id', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('sender_id', sa.String(length=64), nullable=True),
    sa.Column('recipient_type', sa.String(length=16), nullable=True),
    sa.Column('recipient_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collaboration_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collaboration_messages_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_dispatch_id'), ['dispatch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_handoff_id'), ['handoff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_recipient_type'), ['recipient_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_sender_type'), ['sender_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_messages_task_id'), ['task_id'], unique=False)
        batch_op.create_index('uq_collaboration_messages_dedupe_key', ['dedupe_key'], unique=True, sqlite_where=sa.text('dedupe_key IS NOT NULL'), postgresql_where=sa.text('dedupe_key IS NOT NULL'))

    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('sender_id', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_message_id', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_parent_message_id'), ['parent_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_type'), ['sender_type'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=64), nullable=True),
    sa.Column('requirement_policy', sa.JSON(), nullable=True),
    sa.Column('collaboration_config', sa.JSON(), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('local_git_url', sa.String(length=500), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('develop_branch', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_type'), ['project_type'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('requirement_type', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('from_agent', sa.String(length=64), nullable=True),
    sa.Column('to_agent', sa.String(length=64), nullable=True),
    sa.Column('follow_up_from_requirement_id', sa.String(length=64), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('related_files', sa.JSON(), nullable=False),
    sa.Column('max_response_tokens', sa.Integer(), nullable=False),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.Column('last_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_from_agent'), ['from_agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_requirement_type'), ['requirement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_to_agent'), ['to_agent'], unique=False)
        batch_op.create_index('uq_requirements_follow_up_from_requirement_id', ['follow_up_from_requirement_id'], unique=True, sqlite_where=sa.text('follow_up_from_requirement_id IS NOT NULL'), postgresql_where=sa.text('follow_up_from_requirement_id IS NOT NULL'))

    op.create_table('runners',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('allow_hardware_access', sa.Boolean(), nullable=False),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runners_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_runners_status'), ['status'], unique=False)

    op.create_table('usage_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_task_id'), ['task_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('execution_mode', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('agent_type', sa.String(length=64), nullable=True),
    sa.Column('responsibility', sa.Text(), nullable=True),
    sa.Column('modules', sa.JSON(), nullable=False),
    sa.Column('runner_id', sa.String(length=64), nullable=True),
    sa.Column('runner_name', sa.String(length=200), nullable=True),
    sa.Column('permission_level', sa.String(length=8), nullable=False),
    sa.Column('read_paths', sa.JSON(), nullable=False),
    sa.Column('write_paths', sa.JSON(), nullable=False),
    sa.Column('max_tokens_per_task', sa.Integer(), nullable=True),
    sa.Column('max_cost_per_day', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_permission_level'), ['permission_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_runner_id'), ['runner_id'], unique=False)

    op.create_table('project_ai_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'config_id', name='uq_project_ai_providers_project_config_id')
    )
    with op.batch_alter_table('project_ai_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_ai_providers_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_ai_providers_project_id'), ['project_id'], unique=False)

    op.create_table('project_computer_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('runner_id', sa.String(length=64), nullable=True),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'config_id', name='uq_project_computer_nodes_project_config_id')
    )
    with op.batch_alter_table('project_computer_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_computer_nodes_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_computer_nodes_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_computer_nodes_runner_id'), ['runner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_computer_nodes_status'), ['status'], unique=False)

    op.create_table('project_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('accepted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_invites_accepted_by_user_id'), ['accepted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_invites_invited_by_user_id'), ['invited_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_invites_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_invites_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_invites_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_invites_token'), ['token'], unique=True)

    op.create_table('project_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('last_project_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_project_path', sa.String(length=500), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_user')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_user_id'), ['user_id'], unique=False)

    op.create_table('requirement_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('requirement_id', sa.String(length=64), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('sender_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status_after_reply', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_messages_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_messages_sender_type'), ['sender_type'], unique=False)

    op.create_table('project_thread_workstations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('computer_node_id', sa.String(length=64), nullable=True),
    sa.Column('ai_provider_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'config_id', name='uq_project_thread_workstations_project_config_id')
    )
    with op.batch_alter_table('project_thread_workstations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_thread_workstations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_thread_workstations_ai_provider_id'), ['ai_provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_thread_workstations_computer_node_id'), ['computer_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_thread_workstations_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_thread_workstations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_thread_workstations_status'), ['status'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('related_issue', sa.String(length=100), nullable=True),
    sa.Column('assignee_agent_id', sa.String(length=64), nullable=True),
    sa.Column('reviewers', sa.JSON(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assignee_agent_id'), ['assignee_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_branch'), ['branch'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_title'), ['title'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=4), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approver_user_id', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_approver_user_id'), ['approver_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_task_id'), ['task_id'], unique=False)

    op.create_table('context_health_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('usage_ratio', sa.Float(), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('conversation_turns', sa.Integer(), nullable=False),
    sa.Column('files_loaded_count', sa.Integer(), nullable=False),
    sa.Column('failed_retry_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_health_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_health_records_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_health_records_health'), ['health'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_health_records_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_health_records_task_id'), ['task_id'], unique=False)

    op.create_table('handoffs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('handoff_from', sa.String(length=64), nullable=True),
    sa.Column('handoff_to', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handoffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handoffs_handoff_from'), ['handoff_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_handoffs_handoff_to'), ['handoff_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_handoffs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_handoffs_task_id'), ['task_id'], unique=False)

    op.create_table('task_dispatches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('workstation_id', sa.String(length=64), nullable=False),
    sa.Column('workstation_name', sa.String(length=200), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('computer_node_id', sa.String(length=64), nullable=True),
    sa.Column('ai_provider_id', sa.String(length=64), nullable=True),
    sa.Column('runner_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dispatched_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['dispatched_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dispatches_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dispatches_ai_provider_id'), ['ai_provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dispatches_computer_node_id'), ['computer_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dispatches_dispatched_by_user_id'), ['dispatched_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dispatches_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dispatches_runner_id'), ['runner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dispatches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dispatches_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dispatches_workstation_id'), ['workstation_id'], unique=False)

    op.create_table('task_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_events_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_events_event_type'))

    op.drop_table('task_events')
    with op.batch_alter_table('task_dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dispatches_workstation_id'))
        batch_op.drop_index(batch_op.f('ix_task_dispatches_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_dispatches_status'))
        batch_op.drop_index(batch_op.f('ix_task_dispatches_runner_id'))
        batch_op.drop_index(batch_op.f('ix_task_dispatches_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_dispatches_dispatched_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_dispatches_computer_node_id'))
        batch_op.drop_index(batch_op.f('ix_task_dispatches_ai_provider_id'))
        batch_op.drop_index(batch_op.f('ix_task_dispatches_agent_id'))

    op.drop_table('task_dispatches')
    with op.batch_alter_table('handoffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handoffs_task_id'))
        batch_op.drop_index(batch_op.f('ix_handoffs_project_id'))
        batch_op.drop_index(batch_op.f('ix_handoffs_handoff_to'))
        batch_op.drop_index(batch_op.f('ix_handoffs_handoff_from'))

    op.drop_table('handoffs')
    with op.batch_alter_table('context_health_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_health_records_task_id'))
        batch_op.drop_index(batch_op.f('ix_context_health_records_project_id'))
        batch_op.drop_index(batch_op.f('ix_context_health_records_health'))
        batch_op.drop_index(batch_op.f('ix_context_health_records_agent_id'))

    op.drop_table('context_health_records')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_task_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_project_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_level'))
        batch_op.drop_index(batch_op.f('ix_approvals_approver_user_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_action'))

    op.drop_table('approvals')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_module'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_branch'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_agent_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('project_thread_workstations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_thread_workstations_status'))
        batch_op.drop_index(batch_op.f('ix_project_thread_workstations_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_thread_workstations_config_id'))
        batch_op.drop_index(batch_op.f('ix_project_thread_workstations_computer_node_id'))
        batch_op.drop_index(batch_op.f('ix_project_thread_workstations_ai_provider_id'))
        batch_op.drop_index(batch_op.f('ix_project_thread_workstations_agent_id'))

    op.drop_table('project_thread_workstations')
    with op.batch_alter_table('requirement_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_messages_sender_type'))
        batch_op.drop_index(batch_op.f('ix_requirement_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_messages_requirement_id'))

    op.drop_table('requirement_messages')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_status'))
        batch_op.drop_index(batch_op.f('ix_project_members_role'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('project_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_invites_token'))
        batch_op.drop_index(batch_op.f('ix_project_invites_status'))
        batch_op.drop_index(batch_op.f('ix_project_invites_role'))
        batch_op.drop_index(batch_op.f('ix_project_invites_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_invites_invited_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_invites_email'))
        batch_op.drop_index(batch_op.f('ix_project_invites_accepted_by_user_id'))

    op.drop_table('project_invites')
    with op.batch_alter_table('project_computer_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_computer_nodes_status'))
        batch_op.drop_index(batch_op.f('ix_project_computer_nodes_runner_id'))
        batch_op.drop_index(batch_op.f('ix_project_computer_nodes_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_computer_nodes_config_id'))

    op.drop_table('project_computer_nodes')
    with op.batch_alter_table('project_ai_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_ai_providers_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_ai_providers_config_id'))

    op.drop_table('project_ai_providers')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_runner_id'))
        batch_op.drop_index(batch_op.f('ix_agents_role'))
        batch_op.drop_index(batch_op.f('ix_agents_provider'))
        batch_op.drop_index(batch_op.f('ix_agents_permission_level'))
        batch_op.drop_index(batch_op.f('ix_agents_name'))

    op.drop_table('agents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_logs_task_id'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_status'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_provider'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_model'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_agent_id'))

    op.drop_table('usage_logs')
    with op.batch_alter_table('runners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runners_status'))
        batch_op.drop_index(batch_op.f('ix_runners_name'))

    op.drop_table('runners')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index('uq_requirements_follow_up_from_requirement_id', sqlite_where=sa.text('follow_up_from_requirement_id IS NOT NULL'), postgresql_where=sa.text('follow_up_from_requirement_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_requirements_to_agent'))
        batch_op.drop_index(batch_op.f('ix_requirements_title'))
        batch_op.drop_index(batch_op.f('ix_requirements_task_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_status'))
        batch_op.drop_index(batch_op.f('ix_requirements_requirement_type'))
        batch_op.drop_index(batch_op.f('ix_requirements_project_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_priority'))
        batch_op.drop_index(batch_op.f('ix_requirements_module'))
        batch_op.drop_index(batch_op.f('ix_requirements_from_agent'))

    op.drop_table('requirements')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_type'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_type'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_project_id'))
        batch_op.drop_index(batch_op.f('ix_messages_parent_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_messages_entity_type'))
        batch_op.drop_index(batch_op.f('ix_messages_entity_id'))

    op.drop_table('messages')
    with op.batch_alter_table('collaboration_messages', schema=None) as batch_op:
        batch_op.drop_index('uq_collaboration_messages_dedupe_key', sqlite_where=sa.text('dedupe_key IS NOT NULL'), postgresql_where=sa.text('dedupe_key IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_task_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_status'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_sender_type'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_recipient_type'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_project_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_handoff_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_dispatch_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_approval_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_messages_agent_id'))

    op.drop_table('collaboration_messages')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_task_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
